---
- name: Clone the backoffice repo at specific tag/commit
  ansible.builtin.git:
    repo: "{{ somoffice_role_backoffice_repo }}"
    dest: "{{ somoffice_role_local_path }}"
    version: "{{ somoffice_role_backoffice_version }}"
    force: true
  register: gitresult
  tags:
    - sombackoffice
    - build

- name: Render the template .env
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ somoffice_role_local_path }}/.env"
    mode: '0600'
  tags:
    - sombackoffice
    - build

- name: Install npm dependencies
  community.general.npm:
    path: "{{ somoffice_role_local_path }}"
    state: present
  tags:
    - sombackoffice
    - build

- name: Build the backoffice
  community.general.npm:
    path: "{{ somoffice_role_local_path }}"
    state: present
    production: true
  tags:
    - sombackoffice
    - build
